<div class="no-right-bar">
    <!-- main content -->
    <div id="page-content">
    <?php
    $title = 'Add new Employee';
     $this->headTitle($title);
     ?>
      <h1 id="page-header"><?php echo $this->escapeHtml($title); ?></h1>
      <div class="fluid-container">
        <section class="" id="widget-grid">
            <div class="row" style="margin-left: -15px;">
            <article class="col-md-12 sortable-grid ui-sortable">
                <div id="widget-id-1" class="jarviswidget jarviswidget-sortable" role="widget">
                    <header role="heading">                         
                    </header>
                    <div class="message">
                      <?php
                          echo $message;
                      ?>
                    </div>
                    <div class="error">
                      <?php
                          echo $error;
                     ?>
                    </div>                    
                    <div role="content" style="display: block;">
                        <div class="inner-spacer">
                            <?php
                              //echo '<pre>'; print_r($error); echo '</pre>';
                              $form->setAttribute('action', $this->url('admin/employee/add', array('action' => 'add')));
                              $form->prepare();

                              echo $this->form()->openTag($form);
                              // user below code to display form fields
                              //echo $this->formHidden($form->get('employee_id'));
                              echo $this->formRow($form->get('department_id'));
                              echo $this->formRow($form->get('first_name'));
                              echo $this->formRow($form->get('last_name'));
                              echo $this->formRow($form->get('email'));
                              echo $this->formRow($form->get('password'));
                              echo $this->formRow($form->get('is_active'));
                              echo $this->formRow($form->get('dashboard'));
                              echo $this->formRow($form->get('is_driver'));
                              echo $this->formRow($form->get('roles'));
                              echo $this->formSubmit($form->get('submit'));
                              // or use the below code
                              //echo $this->formCollection($form);
                              echo $this->form()->closeTag();
                          ?>

                        </div>
                </div>
                </div>
            </article>
        </div>
        </section>
    </div>		
</div>
<!-- end main content -->
</div>