<!-- main content -->
<div id="page-content">
<?php
$title = 'Employees';
 $this->headTitle($title);
 ?>
 <h1 id="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<a href="/admin/employee/add">Add Employee</a>
<table class="table" style="font-size: 11px;">
 <tr>
     <th>employee id</th>
     <th>department id</th>
     <th>first name</th>
     <th>last name</th>
     <th>email</th>
     <th>password</th>
     <th>is active</th>
     <th>dashboard</th>
     <th>is driver</th>
 </tr>
 <?php foreach ($employees as $employee) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($employee['employee_id']);?></td>
     <td><?php echo $this->escapeHtml($employee['department_id']);?></td>
     
     <td><a href="/admin/employee/update/<?php echo $this->escapeHtml($employee['employee_id']);?>"><?php echo $this->escapeHtml($employee['first_name']);?></a></td>
     <td><a href="/admin/employee/update/<?php echo $this->escapeHtml($employee['employee_id']);?>"><?php echo $this->escapeHtml($employee['last_name']);?></a></td>
     <td><?php echo $this->escapeHtml($employee['email']);?></td>
     <td><?php echo $this->escapeHtml($employee['password']);?></td>
     <td><?php echo ($this->escapeHtml($employee['is_active'])) ? 'active' : 'non-active'; ?></td>
     <td><?php echo $this->escapeHtml($employee['dashboard']);?></td>
     <td><?php echo ($this->escapeHtml($employee['is_driver'])) ? 'true' : 'false'; ?></td>
     <?php /*<td><a href="<?php echo $this->url('admin/employees',
        array('action'=>'update', 'id' => $employee->employee_id));?>">Edit</a>
        <a href="<?php echo $this->url('admin/employees',
        array('action'=>'delete', 'id' => $employee->employee_id));?>">Delete</a>      </td>
        */
     ?>
 </tr>
 <?php endforeach; ?>
 </table>
		
</div>
<!-- end main content -->