<div class="jarviswidget login">
    <!-- content goes here -->
    <div id="main-content">
        <div class="widget alert adjusted alert-error">
            <!--<button class="close" data-dismiss="alert">×</button>-->
            <i class="cus-cross-octagon"></i>
            <strong>Error!</strong> <?php echo $this->translate('Invalid token'); ?>.
        </div>
    </div>
    <!-- end content goes here -->
</div>
