<div id="main-content">
    <div style="width:50%;margin: 40px  auto;vertical-align: middle;/* margin-top: 40px; */">
        <div class="alert adjusted alert-success">
            <!--<button class="close" data-dismiss="alert">×</button>-->
            <i class="cus-accept"></i>
            <strong><?php echo $this->translate('Success'); ?></strong>

            <?php echo $this->translate(' You password has been reset, you will be shortly redirect to login page.'); ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    window.setTimeout(function() {
        window.location.href = "/admin";
    }, 5000)
</script>    