<div class="jarviswidget login">
    <header>
        <h2><?php echo $this->translate('Forgot your password?'); ?></h2>
    </header>

    <div class="widget alert alert-info adjusted">
        <i class="cus-exclamation"></i>
        <strong><?php echo $this->translate('Forgot password? Enter your email address'); ?></strong>
    </div>
    <?php if (isset($error)) { ?>
        <div class="widget alert adjusted alert-error">
            <button class="close" data-dismiss="alert">×</button>
            <i class="cus-cross-octagon"></i>
            <strong><?php echo $this->translate('Error!'); ?></strong> 
            <?php echo $this->translate('Email is not exist in our system.'); ?>
        </div>
    <?php } ?>
    <!-- content goes here -->
    <div id="main-content">

        <?php
        $form = $this->form;
        $form->prepare();
        //$form->setAttribute('action', $this->url(NULL, array('controller' => 'Login', 'action' => 'process')));
        $form->setAttribute('method', 'post');
        echo $this->form()->openTag($form);
        ?>
        <div class = "form-group">
            <?php
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?>
        </div>

        <div class="form-group no-border">
            <div style="text-align: right;">
                <?php echo $this->formElement($form->get('submit')); ?>
            </div>
        </div>

        <?php
        echo $this->form()->closeTag($form);
        ?>
    </div>
    <!-- end content goes here -->
</div>
