<div id="main-content">
    <div style="width:50%;margin: 40px  auto;vertical-align: middle;/* margin-top: 40px; */">
        <div class="alert adjusted alert-success">
            <!--<button class="close" data-dismiss="alert">×</button>-->
            <i class="cus-accept"></i>
            <?php echo $this->translate('An email with instructions has been sent to you. '); ?>
        </div>
        <a href="<?php echo $this->url('admin'); ?>" class="btn btn-primary btn-xs"><?php echo $this->translate('Click to get back on the login page.') ?></a>
    </div>
</div>
