<div class="jarviswidget login">
    <header>
        <h2><?php echo $this->translate('New Password'); ?></h2>
    </header>

    <div class="widget alert alert-info adjusted">
        <i class="cus-exclamation"></i>
        <strong><?php echo $this->translate('Please type in your new password'); ?></strong>
    </div>
    <!-- content goes here -->
    <div id="main-content">

        <?php
        $form = $this->form;
        $form->prepare();
        //$form->setAttribute('action', $this->url(NULL, array('controller' => 'Login', 'action' => 'process')));
        $form->setAttribute('method', 'post');
        echo $this->form()->openTag($form);
        ?>
        <div class = "form-group">
            <?php
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>
        </div>

        <div class = "form-group">
            <?php
            echo $this->formElement($form->get('confirm_password'));
            echo $this->formElementErrors($form->get('confirm_password'));
            ?>
        </div>

        <div class="form-group no-border">
            <div style="text-align: right;">
                <?php echo $this->formElement($form->get('submit')); ?>
            </div>
        </div>

        <?php
        echo $this->form()->closeTag($form);
        ?>
    </div>
    <!-- end content goes here -->
</div>
