<?php require_once 'header.inc.php'; ?>

<div id="main" role="main" class="container-fluid">

    <div class="contained">
        <!-- aside -->	
        <aside>	

            <!-- search box -->
            <div class="main-search">
                <label for="main-search"><i class="icon-search"></i></label>
                <input id="main-search" type="text" placeholder="Search...">
            </div>
            <div class="divider"></div>
            <!-- end search box -->

            <!-- aside item: Mini profile -->
            <div class="my-profile">
                <a href="javascript:void(0)" class="my-profile-pic">
                    <img src="/theme/img/avatar/avatar_0.jpg" alt="" />
                </a>
                <span class="first-child">
                    Welcome 
                    <strong>
                        <?php
                        $sessionEmployoeeInfo = new \Zend\Session\Container('employee_info');
                        echo $sessionEmployoeeInfo->name . '!';
                        ?>
                    </strong>
                </span>
                <!--<span><a href="<?php //echo $this->url('admin/employee/profile')   ?>">Edit Profile </a></span>-->
            </div>
            <div class="divider"></div>
            <!-- end aside item: Mini profile -->

            <!-- aside item: Menu -->
            <div class="sidebar-nav-fixed">

                <ul class="menu" id="accordion-menu-js">
                    <li class="current">
                        <a href="javascript:void(0)"><i class="icon-off"></i>Dashboard <span class="badge">2</span></a>
                        <ul>
                            <li>
                                <a href="<?php echo $this->url('admin/dashboard') ?>" class="expanded">Dashboard</a>
                            </li>
                             <li>
                                <a href="<?php echo $this->url('admin/employees') ?>" >Employee Management</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('admin/departments') ?>" >Department Management</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('admin/logout') ?>" >Logout</a>
                            </li>
                        </ul>
                    </li>
                    <li class="">
                        <a href="inbox.html"><i class="icon-envelope"></i>Inbox</a>
                    </li>
                    <li class="">
                        <a href="javascript:void(0)"><i class="icon-check"></i>Forms<span class="badge">3</span></a>
                        <ul>
                            <li>
                                <a href="forms.html">Form Elements</a>
                            </li>
                            <li>
                                <a href="validation.html">Validation</a>
                            </li>
                            <li>
                                <a href="wizard.html">Wizards</a>
                            </li>
                        </ul>
                    </li>
                    <li class="">
                        <a href="javascript:void(0)"><i class="icon-user"></i>Interface<span class="badge">3</span></a>
                        <ul>
                            <li>
                                <a href="interface.html">Interface Elements</a>
                            </li>
                            <li>
                                <a href="buttons.html">Buttons &amp; Icons</a>
                            </li>
                            <li>
                                <a href="tables.html">Tables</a>
                            </li>
                        </ul>
                    </li>
                    <li class="">
                        <a href="javascript:void(0)"><i class="icon-signal"></i>Charts &amp; Graphs<span class="badge">3</span></a>
                        <ul>
                            <li>
                                <a href="basic_charts.html">Basic Charts</a>
                            </li>
                            <li>
                                <a href="adv_charts.html">Advanced Charts</a>
                            </li>
                            <li>
                                <a href="raphael.html">Raphael Engine</a>
                            </li>
                        </ul>
                    </li>
                    <li class="">
                        <a href="widgets.html"><i class="icon-refresh"></i>Smart Widgets</a>
                    </li>
                    <li class="">
                        <a href="javascript:void(0)"><i class="icon-plus"></i>Bonus<span class="badge">4</span></a>
                        <ul>
                            <li>
                                <a href="invoice.html">Invoice</a>
                            </li>
                            <li>
                                <a href="typography.html">Typography</a>
                            </li>
                            <li>
                                <a href="chat.html">Chat</a>
                            </li>
                            <li>
                                <a href="error-page.html">Error Page</a>
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>
            <div class="divider"></div>
            <!-- end aside item: Menu -->

            <!-- aside item: Inbox -->
            <!-- inbox message 1-->
            <div class="mini-inbox">
                <div class="alert inbox">
                    <button type="button" class="close" data-dismiss="alert">
                        ×
                    </button>

                    <a href="javascript:void(0)">
                        <img src="/theme/img/email-important.png" width="22" height="18" alt="important mail" />
                        From:David S...
                    </a>
                    Dear Victoria, Congratulations! You work has been uploade...
                </div>
                <!-- inbox message 2-->
                <div class="alert inbox">
                    <button type="button" class="close" data-dismiss="alert">
                        ×
                    </button>
                    <a href="javascript:void(0)">
                        <img src="/theme/img/email-unread.png" width="22" height="18" alt="important mail" />
                        Re:Last Year...
                    </a>
                    Hey Vicky, find attached! Thx :-)
                </div>
                <!-- inbox message 3-->
                <div class="alert inbox last-child">
                    <button type="button" class="close" data-dismiss="alert">
                        ×
                    </button>
                    <a href="javascript:void(0)">
                        <img src="/theme/img/email-unread.png" width="22" height="18" alt="important mail" />
                        Company Party
                    </a>
                    Hi, You have been cordially invited to join new year...
                </div>

            </div>
            <div class="divider"></div>
            <!-- end aside item: Inbox -->

            <!-- aside item: Tiny Stats -->
            <div class="number-stats">
                <ul>
                    <li>4579<span>visitors</span></li>
                    <li>571<span>orders</span></li>
                    <li>879<span>reviews</span></li>
                </ul>
            </div>
            <div class="divider"></div>
            <!-- end aside item: Tiny Stats -->

            <!-- aside buttons -->
            <div class="aside-buttons">
                <a href="javascript:void(0)" title="" class="btn btn-primary">Create an Invoice</a>
            </div>
            <div class="divider"></div>
            <!-- end aside buttons -->
        </aside>
        <!-- aside end -->

        <?php echo $this->content; ?>

        <!-- aside right on high res -->
        <aside class="right">

            <!-- sparkline stats -->
            <ul class="mystats indented">
                <li class="first">
                    <h1><span>My Balance:</span>$17,349</h1>
                    <div class="mychart" id="balance" style="width:35px"></div>
                </li>
                <li>
                    <h1><span>Impressions:</span>145k+</h1>
                    <div class="mychart" id="clicks" style="width:35px"></div>
                </li>
                <li>
                    <h1><span>Subscribers:</span>1,120</h1>
                    <div class="mychart" id="subscribe" style="width:35px"></div>
                </li>
                <li class="last">
                    <h1><span>Support Ticket:</span>945+</h1>
                    <div class="mychart" id="support" style="width:35px"></div>
                </li>
            </ul>
            <div class="divider"></div>
            <!-- end sparkline stats -->

            <!-- aside progress bars -->
            <ul class="indented aside-progress-stats">
                <li>
                    <!-- easy pie chart -->
                    <div class="easypie">
                        <div class="percentage" data-percent="68">
                            <span>68</span>%
                        </div>
                        <div class="easypie-text">
                            Server load
                        </div>
                    </div>
                    <!-- end easy pie chart -->
                </li>
                <li>
                    <strong>Data Restored</strong><strong class="pull-right">90%</strong>
                    <div class="progress progress-danger slim"><div class="bar" data-percentage="90"></div></div>
                </li>
                <li>
                    <strong>Recovering IDE</strong><strong class="pull-right">66%</strong>
                    <div class="progress progress-info slim"><div class="bar" data-percentage="66"></div></div>
                </li>
                <li>
                    <strong>DLL Construction</strong><strong class="pull-right">48%</strong>
                    <div class="progress progress-info slim"><div class="bar" data-percentage="48"></div></div>
                </li>
                <li>
                    <strong>Machine Req</strong><strong class="pull-right">33%</strong>
                    <div class="progress progress-info slim"><div class="bar" data-percentage="33"></div></div>
                </li>
            </ul>
            <div class="divider"></div>
            <!-- end aside progress bars -->

            <!-- date picker -->
            <div id="datepicker"></div>
            <div class="divider"></div>
            <!-- end date picker -->

            <!-- aside buttons -->
            <div class="aside-buttons">
                <a href="javascript:void(0);" title="" class="btn btn-info">Create an Invoice</a>
                <a href="javascript:void(0);" title="" class="btn btn-success">New Campaign</a>
                <a href="javascript:void(0);" title="" class="btn btn-danger">Delete Progress</a>
            </div>
            <div class="divider"></div>
            <!-- end aside buttons -->
        </aside>

        <!-- end aside right -->
    </div>

</div><!--end fluid-container-->
<div class="push"></div>
</div>
<!-- end .height wrapper -->
<?php require_once 'footer.inc.php'; ?>
</body>
</html>
