<div class="no-right-bar">
    <!-- main content -->
    <div id="page-content">
    <?php
    $title = 'Add new Department';
     $this->headTitle($title);
     ?>
     <h1 id="page-header"><?php echo $this->escapeHtml($title); ?></h1>
     <?php 
     //echo '<pre>'; print_r($errors); echo '</pre>';
     $form->setAttribute('action', $this->url('admin/department/add', array('action' => 'add')));
     $form->prepare();

     echo $this->form()->openTag($form);
     // user below code to display form fields 
     echo $this->formRow($form->get('title'));
     echo $this->formRow($form->get('is_active'));
     echo $this->formSubmit($form->get('submit'));
     // or use the below code
     //echo $this->formCollection($form);
     echo $this->form()->closeTag();
    ?>

    </div>
    <!-- end main content -->
</div>