<div class="no-right-bar">
<!-- main content -->
<div id="page-content">
<?php
$title = 'Department Management';
 $this->headTitle($title);
 ?>
 <h1 id="page-header"><?php echo $this->escapeHtml($title); ?></h1>
 <div class="fluid-container">
        <section class="" id="widget-grid">
        <div class="row">
            <article class="col-md-12 sortable-grid ui-sortable">
                <div id="widget-id-1" class="jarviswidget jarviswidget-sortable" role="widget">
                    <header role="heading">
                        <h5><a href="/admin/department/add">Add Department</a></h5>                           
                    </header>
                <div role="content" style="display: block;">
                    <div class="inner-spacer">


<table id="dtable" class="table table-striped table-bordered responsive dataTable" aria-describedby="dtable_info">
    <thead
        <tr>     
            <th>Department ID</th>
            <th>Title</th>     
            <th>Status</th>            
        </tr>
    </thead>
    <tbody role="alert" aria-live="polite" aria-relevant="all">
    <?php foreach ($departments as $department) : ?>
    <tr>     
        <td><?php echo $this->escapeHtml($department['department_id']);?></td>

        <td><a href="/admin/department/update/<?php echo $this->escapeHtml($department['department_id']);?>"><?php echo $this->escapeHtml($department['title']);?></a></td>          
        <td><?php echo ($this->escapeHtml($department['is_active'])) ? 'active' : 'non-active'; ?></td>        
    </tr>
    <?php endforeach; ?>
    </tbody>
 </table>
 </div>
                </div>
                </div>
            </article>
        </div>
        </section>
    </div>		
</div>
<!-- end main content -->
</div>