<!-- main content -->
<div id="page-content">
<?php
$title = 'Departments';
 $this->headTitle($title);
 ?>
 <h1 id="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<a href="/admin/department/add">Add Department</a>
<table class="table">
 <tr>     
     <th>department id</th>
     <th>title</th>     
     <th>is active</th>
     <th>date created</th>
     <th>date modified</th>
 </tr>
 <?php foreach ($departments as $department) : ?>
 <tr>     
     <td><?php echo $this->escapeHtml($department['department_id']);?></td>
     
     <td><a href="/admin/department/update/<?php echo $this->escapeHtml($department['department_id']);?>"><?php echo $this->escapeHtml($department['title']);?></a></td>          
     <td><?php echo ($this->escapeHtml($department['is_active'])) ? 'active' : 'non-active'; ?></td>
     <td><?php echo $this->escapeHtml($department['date_created']);?></td>
     <td><?php echo $this->escapeHtml($department['date_modified']); ?></td>
     <?php /*<td><a href="<?php echo $this->url('admin/employees',
        array('action'=>'update', 'id' => $employee->employee_id));?>">Edit</a>
        <a href="<?php echo $this->url('admin/employees',
        array('action'=>'delete', 'id' => $employee->employee_id));?>">Delete</a>      </td>
        */
     ?>
 </tr>
 <?php endforeach; ?>
 </table>
		
</div>
<!-- end main content -->